name: delivery_factory_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  get: ^4.7.2
  http: ^1.3.0
  logging: ^1.3.0
  shared_preferences: ^2.5.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

# Add this section for assets
assets:
  - assets/images/
